apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-splash2x-fft
  labels:
    name: pasec-splash2x-fft
spec:
  template:
    spec:
      containers:
      - image: anakli/parsec:splash2x-fft-native-reduced
        name: parsec-splash2x-fft
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 0-8 ./bin/parsecmgmt -a run -p splash2x.fft -i native -n 8"]
        resources:
          requests:
            cpu: "6000m"
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-c-8core"
