apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-canneal
  labels:
    name: pasec-canneal
spec:
  template:
    spec:
      containers:
      - image: anakli/parsec:canneal-native-reduced
        name: parseccanneal
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 3-5 ./bin/parsecmgmt -a run -p canneal -i native -n 3"]
        resources:
          requests:
            cpu: "2500m"
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-c-8core"
